sfilename = 'saveData.mat';
save(sfilename,'index',...
'body',...
'headlines',...
'idx',...
'stance',...
'body',...
'bodyCells',...
'words',...
'counts',...
'dictionary',...
'docterm');
svdfilename = 'svdData.mat';
save(svdfilename,...
'S',...
'D',...
's',...
'd',...
'tfidf',...
'highlight_terms_tfidf',...
'highlight_terms_pure',...
'selected_articles_pure_transpose',...
'selected_articles_pure',...
'selected_articles_tfidf_transpose',...
'selected_articles_tfidf'...
);
nnmffilename = 'nnfmData.mat';
save(nnmffilename,...
'Wn',...
'Hn',...
'Dn',...
'wn',...
'hn',...
'dn');

